apply plugin: 'com.android.application'

def releaseSigningProperties = new Properties()
def releaseSigningFile = rootProject.file('keystore.properties')
def hasReleaseSigning = releaseSigningFile.exists()
if (hasReleaseSigning) {
    releaseSigningFile.withInputStream { releaseSigningProperties.load(it) }
}

android {
    namespace 'com.noteshadow.app'
    compileSdk 31
    buildToolsVersion '31.0.0'

    defaultConfig {
        applicationId 'com.noteshadow.app3'
        minSdk 23
        targetSdk 31
        versionCode 6
        versionName '0.5.1'
    }

    signingConfigs {
        if (hasReleaseSigning) {
            release {
                storeFile rootProject.file(releaseSigningProperties['storeFile'])
                storePassword releaseSigningProperties['storePassword']
                keyAlias releaseSigningProperties['keyAlias']
                keyPassword releaseSigningProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
